### ISSUE TITLE
Make project compatible with Python 3

### ISSUE THREAD

**Issue by mre** [mre/timelapse#21]
## Feature Request Type

- [X] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

It would be great if we could support Python 3. In #7, @mepda mentioned some problems he encountered while trying it. This would be a great first issue for a new contributor.

**Comment by mre** [comment]
Maybe someone could also take over #17, which adds Python 3 support to our CI.

**Comment by janithwanni** [comment]
I will take this up. @mre

**Comment by mre** [comment]
Very nice @janithwanni. Looking forward to your contributions. Feel free to post here in case you run into any issues.

**Comment by janithwanni** [comment]
Hey @mre have you tested this on OSX 10.14.6 with Xcode 11.1 ? I keep getting errors trying to install pyobjc using ```pip install -r requirements.txt``` the error output is attached [here](https://pastebin.com/VZ3qCYLC) and this [issue](https://bitbucket.org/ronaldoussoren/pyobjc/issues/274/compile-error-on-python-38-in) from the pyobjc repo in bitbucket seems to be of the similar kind. As mentioned in the comment there, I updated the requirements.txt to upgrade the pyobjc dependencies to 5.3 and the issue was resolved with regards to installing. 

will check whether the functionality is up and running 😅

**Comment by mre** [comment]
Haven't tested it there. Could well be that we have to update pyobjc to support it. Yeah let's see if it runs with the newest version.

**Comment by mre** [comment]
Quick update: we got support for Python 3.7 thanks to #21. Github Actions pipeline is here: https://github.com/mre/timelapse/blob/master/.github/workflows/pythonapp.yml

**Comment by mre** [comment]
So I think it should all work with 3.7 as the tests pass. If anyone finds an issue, please go ahead and reopen the issue or create a new one. Thanks for investigating @janithwanni.
