### ISSUE TITLE
Creates a massive amount of PNG captures

### ISSUE THREAD

**Issue by jcayzac** [mre/timelapse#51]
The app is eating away all my disk with PNG captures.

As I understand it uses `ffmpeg` anyway, I wonder why you're not simply creating the video directly. E.g. https://gist.github.com/jcayzac/142da3cfa9b00a1d9af2f29260d45930

**Comment by mre** [comment]
Two reasons:

* It might be more fragile. What happens when the timelapse crashes? Will the stream until that point still be watchable? What about locking/hybernating the computer? Will it be able to pick up recording again after that?
* I didn't run into those issues yet and others might not have found the time to work on them. It's an open source project after all, so people work on this in their free-time.

Your script looks interesting. Would you be willing to create a pull request that I could test?

**Comment by mre** [comment]
Ping @jcayzac: would you have time to create a pull request or should we rather close this issue? ☺️

**Comment by jcayzac** [comment]
Hey @mre !
Sorry I haven't replied to your messages, I've been drowning in notifications in the past few months and just recently managed to tame them back to reasonnable levels.
Unfortunately I don't think I can contribute any development time for at least a few months. Feel free to close the issue!

**Comment by mre** [comment]
No worries at all. 😆 I know what you mean.
