### ISSUE TITLE
timelapse freeze on suspend

### ISSUE THREAD

**Issue by zodman** [mre/timelapse#55]
## Describe the Bug

When my system goes suspend or black screen the timelapse stop of take screenshots

## System Information

 - Operating system: mac
 - Software version: last build

someone else had that problem ?

**Comment by mre** [comment]
Hey @zodman,
when the system goes to sleep, there is nothing the app can do really. It is all up to the process scheduler at this point: 

> [The] app is interrupted exactly where it is that moment if the CPU is actually currently executing code of your app. Your app constantly gets execution time by the task scheduler, that decides which app gets CPU time, on which core, and for how long. Once the system really goes to sleep, the scheduler simply gives no time to your app any longer, thus it will stop execution wherever it is at that moment, which can happen pretty much everywhere. 

(From https://stackoverflow.com/questions/116945/what-happens-to-my-app-when-my-mac-goes-to-sleep)

So all applications including timelapse will go to sleep and be suspended and there is no way around it as far as I can tell (other than preventing the system to go to sleep altogether). 

Just tested on my machine and timelapse simply continues taking screenshot after coming back from sleep mode, so that should work as expected.
Does that help? ☺️

**Comment by zodman** [comment]
yes man!
